spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ecommerceapp
    password: ecommerceapp
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-f0f8kv88nfxt50ot.us.auth0.com/


allowed.origins: http://localhost:4200


okta:
  oauth2:
    audience: http://localhost:8080
    client-id: 5w3wMFVMLQPeaYG3EAnf08GCROr8J3Y0
    issuer: https://dev-f0f8kv88nfxt50ot.us.auth0.com/

server:
  port: 8443  
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeit
    enabled: true

stripe:
  api-key: "pk_test_51SXQVvPVMl4H7fDhBmBdYEjieicvGtmITqkSXp8e7rPg5xz0HgTMaHNx607tlZBHWlDEipxLARajvUSOlfZwHrcE00M2YS6Rjo"
  public-key: ${STRIPE_PUBLIC_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}